### ISSUE TITLE
2 malfunction of occurrences

### ISSUE THREAD

**Issue by hackin88** [UltimateModuleCreator/Umc_Base#1]
Hello Good Afternoon

Performing tests on his program was generated 2 malfunction of occurrences

1)

Notice: Undefined index: entities in /app/code/Umc/Base/Controller/Adminhtml/Module/Edit.php on line 155

2)

$ gunzip hello_Modulocreator02.gz

gzip: hello_Modulocreator02.gz: not in gzip format

Watch the video of the executed process

https://dl.dropboxusercontent.com/u/4109497/out_UMC_Base.ogv.zip

**Comment by UltimateModuleCreator** [comment]
@hackin88 Sorry For the late response. I will take a look and fix the issues.

**Comment by hackin88** [comment]
Hello

In the video I made in step 1 I had not added an entity, so the occurrence of the error

In step 2 the file was not unpacked

As soon as possible I will be testing the new version of the module

Thank you
