### ISSUE TITLE
Error occurrence in the use of the type entities such as image

### ISSUE THREAD

**Issue by cerebrumgit** [UltimateModuleCreator/Umc_Base#10]
Hello good afternoon

As images we see that error

Error occurrence in the use of the type entities such as image

![captura de tela de 2015-12-10 11 53 05](https://cloud.githubusercontent.com/assets/3661079/11717172/cd4330a8-9f35-11e5-8868-f1f20b03ad09.png)
![captura de tela de 2015-12-10 11 53 34](https://cloud.githubusercontent.com/assets/3661079/11717175/cd4a7804-9f35-11e5-89a7-86d61aa19684.png)
![captura de tela de 2015-12-10 11 53 42](https://cloud.githubusercontent.com/assets/3661079/11717173/cd45e636-9f35-11e5-8657-7370f336b9cb.png)
![captura de tela de 2015-12-10 11 54 20](https://cloud.githubusercontent.com/assets/3661079/11717174/cd47ae6c-9f35-11e5-89bb-859c83ff7d59.png)

**Comment by UltimateModuleCreator** [comment]
@cerebrumgit Thanks for reporting this. I will fix it as soon as possible.  
In the mean time, you can try this. Not sure this is the problem but it's worth a shot.  
change this line:  https://github.com/UltimateModuleCreator/Umc_Base/blob/master/Model/Core/Module.php#L473

to 

    $key = $this->_underscore(substr($method, strlen('getHasAttributeType')));

then rebuild your module again.  
If that does not solve it, sorry, but you will have to wait about 2 days. :)

**Comment by UltimateModuleCreator** [comment]
@cerebrumgit I was wrong in the comment above. The issue was in `um/source.xml` It should be fixed now. Thanks for spotting this. Looking forward for other issues from you :).
