### ISSUE TITLE
The file was not uploaded.

### ISSUE THREAD

**Issue by cerebrumgit** [UltimateModuleCreator/Umc_Base#12]
Hello good afternoon

I created a form containing image upload

But when I saved the record is not uploaded image

Or made relative return uploading process

as images

![captura de tela de 2015-12-16 15 57 41](https://cloud.githubusercontent.com/assets/3661079/11849235/05f83880-a40e-11e5-8608-8afa16477e97.png)
![captura de tela de 2015-12-16 15 57 50](https://cloud.githubusercontent.com/assets/3661079/11849236/0604d72a-a40e-11e5-8056-fc013e8a98b4.png)
![captura de tela de 2015-12-16 15 58 46](https://cloud.githubusercontent.com/assets/3661079/11849237/06094b20-a40e-11e5-8199-dd1194321c59.png)
![captura de tela de 2015-12-16 15 58 54](https://cloud.githubusercontent.com/assets/3661079/11849238/060ec9c4-a40e-11e5-9a43-00e7e2af0d4c.png)
![captura de tela de 2015-12-16 16 00 31](https://cloud.githubusercontent.com/assets/3661079/11849273/2f4230b0-a40e-11e5-8fcd-1ea61af4f74f.png)
![captura de tela de 2015-12-16 16 00 41](https://cloud.githubusercontent.com/assets/3661079/11849274/2f45abaa-a40e-11e5-88cb-e427947305a6.png)

**Comment by maderlock** [comment]
This may be because the type is getting set to 'file' instead of 'image'. I think I've seen something similar. I'll try to push up a patch.

**Comment by UltimateModuleCreator** [comment]
This extension is under heavy refactoring right now. The generated extensions form will use ui-components instead of tab based forms so the upload will get changed also.

**Comment by tomdollarmpd** [comment]
just to confirm this is because the form field needs to be of type 'image' rather than 'file'.   Any plans to finish this incredible module off in the near future?

**Comment by UltimateModuleCreator** [comment]
@tomdollarmpd There are plans, there is work in progress, but there isn't very much time. I hope I can pick this up again and deliver at least an MVP compatible with the latest magento version. But I cannot make any commitments for a time frame.

**Comment by tomdollarmpd** [comment]
thanks for your response.  That is absolutely fair enough.  The module as it is has got me out of a hole which was creating entities with cross dependency.  I'm building all the frontend stuff on top which is serving as a valuable lesson in Mage 2 module development :)  Loving your work.

**Comment by UltimateModuleCreator** [comment]
This should be fixed in version 2.0.0-beta1.
