### ISSUE TITLE
Received "Your extension has been created!" Message -- But Extension was Not Created

### ISSUE THREAD

**Issue by astorm** [UltimateModuleCreator/Umc_Base#15]
After filling out the UI for a new module, with a single entity (and that entity has a single field named `name`, Magento reports

> Your extension has been created

But, in fact, despite what the message says, there's **no extension** in `app/code`, and the grid of extensions in empty.  

<img width="1238" alt="screen shot 2015-12-26 at 5 52 38 pm" src="https://cloud.githubusercontent.com/assets/184372/12008584/4b9b37f4-abfa-11e5-85b1-ded84dde9428.png">

No errors of note in my PHP error log, or in any of Magento's logs.  There was this is in `debug.log` -- but it seems unrelated

    [2015-12-27 01:52:51] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
    [2015-12-27 01:52:51] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
    [2015-12-27 01:52:51] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
    [2015-12-27 01:55:02] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
    [2015-12-27 01:55:02] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
    [2015-12-27 01:55:02] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
    [2015-12-27 01:55:03] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_3d41d8cd98f00b204e9800998ecf8427e: Please correct the XML data and try again.  [] []

Digging in deeper to this, but posting now in case it triggers something. 

Using the 2.0 release, installed via the `magento/product-community-edition` package.

**Comment by astorm** [comment]
(Also -- if you have a particular code point where it'd be useful to start debugging, that'd be helpful)

**Comment by astorm** [comment]
Tracked this one down a little -- I don't know about about how UMC is supposed to work behind the scenes to come up with a pull request, **but** as near I can tell, this controller is responsible for saving the module

    app/code/Umc/Base/Controller/Adminhtml/Module/Save.php

However, in 

    public function execute()
    {
        $redirectBack = $this->getRequest()->getParam('back', false);
        /** @var \Umc\Base\Model\Core\Module $module */
        $module = $this->moduleFactory->create();
        try {
            $module->initFromData($this->getRequest()->getPost()->toArray());
            $this->messageManager->addSuccess(__('Your extension has been created!'));
        } catch (\Exception $e) {
            $this->messageManager->addError($e->getMessage());
            $redirectBack = true;
        }
        $pageRedirect = $this->pageRedirectFactory->create();

There's no call to `validate`, `buildModule`, or `save` as there [is here in the 1.x version](https://github.com/tzyganu/UMC1.9/blob/master/app/code/community/Ultimate/ModuleCreator/controllers/Adminhtml/ModulecreatorController.php).

Is this code missing?  Or does UMC do it's creation differently now?

**Comment by UltimateModuleCreator** [comment]
@astorm I'm on vacation with limited acces to the internet and practically no access to a computer. (And I like it) I will investigate this .... aaa... next year. Sorry for the delay

**Comment by astorm** [comment]
@UltimateModuleCreator No worries.  If you have 15 second and it's on the top of your mind -- do you know/recall where the method call that kicks off file writing for the module creator is?

**Comment by UltimateModuleCreator** [comment]
This is where everything begins https://github.com/UltimateModuleCreator/Umc_Base/blob/master/Controller/Adminhtml/Module/Validate.php#L110. Everything should be written in var/umc. There is no more option to install directly

**Comment by astorm** [comment]
@UltimateModuleCreator  Thanks again -- I'll ping you on the second.  Gett off the computer!

**Comment by UltimateModuleCreator** [comment]
@astorm. Thanks...and i was on my phone. I will close it now

**Comment by astorm** [comment]
@UltimateModuleCreator Just checking in -- any chance to review this? Or is UMC still low on the list of things you have time for at the moment

**Comment by UltimateModuleCreator** [comment]
@astorm No, this is top priority on my spare time. Unfortunately the spare time I have is close to zero. Damn work, getting in the way of things that are really important. I added a notice in the readme.md that this is on hold till Magento 2 is stabilized and I get some spare time.

**Comment by astorm** [comment]
No worries @UltimateModuleCreator -- I know how that goes all too well. Hopefully I'll have some of that free time to dig into this as well.

**Comment by maderlock** [comment]
Now that the Magento 2 base is settling down, have either of you got any further with this, @UltimateModuleCreator or @astorm?

**Comment by maderlock** [comment]
Although the message the to user is that creation of module is successful, the path to write the xml and modules files starts with var rather than getting the concrete base path for var.

**Comment by UltimateModuleCreator** [comment]
@maderlock I put project this on hold a while a go for 2 reasons. M2 was changing from day to day and the lack of time to take care of it. M2 being stable solves only half the problem. But you are right, maybe I should find the time to start it again.  
Oh! and thanks for the PR.

**Comment by maderlock** [comment]
@UltimateModuleCreator Thanks for accepting the changes, and I completely understand the lack of time issue - I have a full-time job and three kids under 5. Free time is scarce. However - this module is useful for my job so there's a chance I will be able to help with this module.
