### ISSUE TITLE
[Feature request] Frontend files

### ISSUE THREAD

**Issue by KiuNguyen** [UltimateModuleCreator/Umc_Base#24]
As UMC for M1, it generates frontend files.
It is not implemented in UMC for M2.

Please consider this feature

**Comment by UltimateModuleCreator** [comment]
@KiuNguyen This is in the roadmap. It will be a separate repo with with the files needed to generate frontend files. Most probably will be called `Umc_Frontend`.  
I will close this issue for now since it is not related to the `Umc_Base` module.
