### ISSUE TITLE
Module Installation

### ISSUE THREAD

**Issue by amitradix** [UltimateModuleCreator/Umc_Base#29]
Hi there,

Trust that you are doing well !!

We have tried your module manually as well installer in magento version 2.0.6. Using console its throwing error and using manual i have put zip folder under app folder and then unzip for same as required. But i did not found any module in admin(backend). I have run both the commands as shared in your installation guide.

Can you please help us.

Looking forward to your quick reply.

Best,
Amit

**Comment by UltimateModuleCreator** [comment]
@amitradix Please read the notice in here: https://github.com/UltimateModuleCreator/Umc_Base/blob/master/README.md
The code in this repo is old and outdated. I'm working on a new version now, but It will take a while until it can be used.
