### ISSUE TITLE
Installation suggestion via composer

### ISSUE THREAD

**Issue by hackin88** [UltimateModuleCreator/Umc_Base#3]
Hello

Good afternoon

1)

What would be the procedure that indicates you to install your module in Magento2?

2)

I have not found your module in

https://packagist.org/search/?q=umc

To install via composer

It is my suggestion to release the module via composer

**Comment by UltimateModuleCreator** [comment]
@hackin88 I will release this on packagist as soon as I have a stable version that I'm satisfied with.  
Right now it's in the dev stage and I'm a little behind on the testing.

**Comment by strajeru** [comment]
@hackin88  you should be able to install this extension via composer. The package is not on packagist, but it should work anyway via git.

**Comment by UltimateModuleCreator** [comment]
@hackin88 The extension is not on packagist, but you should be able to install it via composer anyway.

**Comment by cerebrumgit** [comment]
Hello good afternoon

Thanks for answering

Please what is the procedure to install your module via composer?

**Comment by UltimateModuleCreator** [comment]
@cerebrumgit I forgot to post the link. Sorry: https://github.com/UltimateModuleCreator/Umc_Base/wiki/installation
