### ISSUE TITLE
Problems with ACL if name of an entity matches the name of the module

### ISSUE THREAD

**Issue by maderlock** [UltimateModuleCreator/Umc_Base#30]
After installing a module in this situation the admin panel would not load as it complained about non-unique ACL strings.

Either this needs to be handled by adding some suffix to make the string unique, or there should be a warning in the UI.

**Comment by sidealice** [comment]
#31 fix acl duplicate if module name equal to entity name

**Comment by UltimateModuleCreator** [comment]
@maderlock This should be fixed in the new version.
