### ISSUE TITLE
No valid composer.json was found in any branch or tag

### ISSUE THREAD

**Issue by VincentMarmiesse** [UltimateModuleCreator/Umc_Base#32]
Hello,

Thanks for your work!

I'm trying to install your module but I have this issue:
<img width="1301" alt="umc-issue" src="https://cloud.githubusercontent.com/assets/1949412/26325885/0efe1446-3f39-11e7-9091-3886d4f1ba45.png">

Am I doing something wrong?

**Comment by UltimateModuleCreator** [comment]
@VincentMarmiesse Thanks for spotting this. There was a rogue `~` in there. It should work now.
