### ISSUE TITLE
datasource compatiable issue in module creation with Umc

### ISSUE THREAD

**Issue by sivajik34** [UltimateModuleCreator/Umc_Base#6]
prepareDataSource() must be compatible with Magento\Framework\View\Element\UiComponentInterface::prepareDataSource(array $dataSource)

**Comment by tzyganu** [comment]
@sivajik34 Thanks for reporting this and the other issues. The current state of the module is not compatible with the latest magento 2 version. I will take care of these issues and others I found.

**Comment by UltimateModuleCreator** [comment]
@sivajik34 This should be solved in the latest version.
