### ISSUE TITLE
Initial documentation

### ISSUE THREAD

**Issue by cermat** [UltimateModuleCreator/Umc_Base#7]
Thank for module,
Is there any documentation how to install and how to use?

**Comment by UltimateModuleCreator** [comment]
@cermat This module is not yet compatible with the latest magento version. I'm working on this and a new version will be released in the next weeks. I will try to put together a small documentation also.

**Comment by UltimateModuleCreator** [comment]
@cermat You can find some installation instructions [here](https://github.com/UltimateModuleCreator/Umc_Base/wiki).  
After installing you will find a help link in the module, and also each field you need to fill in has a tooltip with explanations.  
Until I finish the user manual for this you can take a look at the [version for magento 1](https://github.com/tzyganu/UMC1.9/wiki). It kind of does the same thing. Some of the fields might be different but not by much.
